# Load modular configs
source-file ~/.config/tmux/conf/keys.conf
source-file ~/.config/tmux/conf/ui.conf
source-file ~/.config/tmux/conf/behaviour.conf
source-file ~/.config/tmux/conf/sessions.conf
source-file ~/.config/tmux/conf/plugins.conf
set -gq allow-passthrough on
set -g visual-activity off
