# TPM & plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'olimorris/tmux-pomodoro-plus'

# Plugin settings
# Don't auto-restore (manual only)
set -g @continuum-restore 'off'

# Still auto-save every 15 minutes
set -g @continuum-save-interval '15'
set -g @resurrect-capture-pane-contents 'on'

set -g @prefix_highlight_fg 'white'
set -g @prefix_highlight_bg '#{?client_prefix,#{@red},#{@bg}}'
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_copy_mode_attr 'fg=black,bg=#{@yellow},bold'

set -g @override_copy_command 'xclip -selection clipboard'

# Initialize TPM
run '~/.tmux/plugins/tpm/tpm'
