# Alt+s to switch sessions
bind -n M-s choose-session
# Create sessions from script
bind C-c run-shell "~/.config/tmux/scripts/create-session.sh"

# FZF popup
set -g @plugin 'sainnhe/tmux-fzf'
TMUX_FZF_LAUNCH_KEY="ff"
TMUX_FZF_OPTIONS="-p -w 90% -h 38% -m"
