# Kanagawa Theme
set -g @bg        "#1F1F28"
set -g @fg        "#7FB4CA"
set -g @black     "#16161D"
set -g @red       "#E46876"
set -g @yellow    "#DCA561"
set -g @green     "#98BB6C"
set -g @fujiWhite "#DCD7BA"

# Status bar

set-option -g status on
set-option -g status-position bottom
set-option -g status-style "bg=#{@bg},fg=#{@fg}"
set-option -g status-left "#[fg=#{@fujiWhite},bg=#{@black},bold] #S #[fg=#{@black},bg=#{@bg}]"
set-window-option -g window-status-format " #I:#W "
set-window-option -g window-status-current-format "#[fg=#{@black},bg=#{@fg}] #I:#W #[fg=#{@fg},bg=#{@bg}]"

# Status bar display (colors use your Kanagawa palette)
set -g @pomodoro_on "#[fg=#{@green}]● #[default]"          # Running Pomodoro
set -g @pomodoro_complete "#[fg=#{@yellow}]✔︎ #[default]"   # On break (complete)
set -g @pomodoro_pause "#[fg=#{@red}]■ #[default]"          # Paused Pomodoro/break
set -g @pomodoro_prompt_break "⏲️ Break?"                   # Waiting to start break
set -g @pomodoro_prompt_pomodoro "⏰ Focus?"                 # Waiting to start Pomodoro

# Position the Pomodoro status in the right status bar
set -g status-right "#{pomodoro_status} #{prefix_highlight} #[fg=#{@black},bg=#{@fg},bold] #(bash ~/.config/tmux/scripts/battery-status.sh) "
set -g status-interval 1  # Refresh every second for countdown smoothness

# Window & titles
set-option -g set-titles on
set-option -g set-titles-string "#{pane_title} | #{window_name}"
