# Kanagawa Theme
set -g @bg        "#1F1F28"
set -g @fg        "#7FB4CA"
set -g @black     "#16161D"
set -g @red       "#E46876"
set -g @yellow    "#DCA561"
set -g @green     "#98BB6C"
set -g @fujiWhite "#DCD7BA"

# Status bar

set-option -g status on
set-option -g status-position top
set-option -g status-style "bg=#{@bg},fg=#{@fg}"
set-option -g status-left "#[fg=#{@fujiWhite},bg=#{@black},bold] #S #[fg=#{@black},bg=#{@bg}]"
set-window-option -g window-status-format " #I:#W "
set-window-option -g window-status-current-format "#[fg=#{@black},bg=#{@fg}] #I:#W #[fg=#{@fg},bg=#{@bg}]"
set-option -g status-right "#{pomodoro_status} #{prefix_highlight} #[fg=#{@black},bg=#{@fg},bold] #( bash ~/.config/tmux/scripts/battery-status.sh) "

# Window & titles
set-option -g set-titles on
set-option -g set-titles-string "#{pane_title} | #{window_name}"
