# Output and appearance
output * bg ~/dotfiles/wallpapers/obito.jpg fill

# Theme (Gruvbox)
set $bg      #282828
set $fg      #ebdbb2
set $yellow  #d79921
set $red     #cc241d
set $green   #98971a
set $blue    #458588
set $aqua    #689d6a
set $gray    #a89984

client.focused $yellow $yellow $bg $yellow
client.focused_inactive $bg $bg $bg $gray
client.unfocused $bg $bg $bg $gray
client.urgent $red $red $bg $fg
client.placeholder $bg $bg $bg $gray

default_border pixel 2
# gaps inner 5
# gaps outer 5

