
# General config
add_newline = false
format = """
$directory$git_branch$git_status$nodejs$rust$python$lua$docker_context$package$conda$memory_usage
$character
"""

# Prompt character
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold blue)"
vimcmd_replace_one_symbol = "[❮](bold purple)"
vimcmd_replace_symbol = "[❮](bold purple)"
vimcmd_visual_symbol = "[❮](bold yellow)"

# Directory
[directory]
truncation_length = 3
read_only = " 󰌾"
style = "blue"

# Git
[git_branch]
symbol = " "
style = "bold purple"

[git_status]
style = "purple"

[git_commit]
tag_symbol = "  "

# Languages (minimal)
[nodejs]
symbol = " "
style = "green"

[rust]
symbol = "󱘗 "
style = "red"

[python]
symbol = " "
style = "yellow"

[lua]
symbol = " "
style = "blue"

# Docker
[docker_context]
symbol = " "
style = "cyan"

# Package version
[package]
symbol = "󰏗 "
style = "bold blue"

# Conda
[conda]
symbol = " "
style = "green"

# Memory usage
[memory_usage]
symbol = "󰍛 "
threshold = 70
style = "bold dimmed white"

# Hostname (optional)
[hostname]
ssh_symbol = " "
style = "dimmed white"

# OS symbols (Linux-focused, trimmed)
[os.symbols]
Arch = " "
Debian = " "
EndeavourOS = " "
Fedora = " "
Garuda = "󰛓 "
Gentoo = " "
Kali = " "
Manjaro = " "
Mint = " "
NixOS = " "
Ubuntu = " "
Void = " "
Windows = "󰍲 "
Unknown = " "
